### ISSUE TITLE
Sentiment Analysis Model

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/DL-Simplified#13]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Sentiment Analysis Model</br>
:red_circle: **Aim** : Analyze the sentiments of the mass from the given dataset. </br>
:red_circle: **Dataset** : https://www.kaggle.com/columbine/imdb-dataset-sentiment-analysis-in-csv-format/download </br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by vaniseth** [comment]
I would like to work on this. Please assign this to me.

**Comment by abhisheks008** [comment]
This issue will be assigned to you once the program starts. Otherwise your contribution will not be counted as a participation in SSOC 2022. See you in the program @vaniseth.

**Comment by CodeFlyAir** [comment]
I would like contribute on this issue. Please assign this to me.

**Comment by abhisheks008** [comment]
Issue assigned to you @CodeFlyAir

**Comment by abhisheks008** [comment]
@CodeFlyAir updates please.

**Comment by abhisheks008** [comment]
Updates please @CodeFlyAir

**Comment by deeptiii13** [comment]
Hey, I would like to work on this issue.
Full name : Deepti Chhabra
GitHub Profile Link : https://github.com/deeptiii13
Email ID : deeptichhabra28@gmail.com
Approach for this Project : Extracting the features using TF-IDF and training different classification models (Logistic Regression, SVM, LDA, Naive Bayes) in order to find the best fit model.
What is your participant role? SWOC 3.0

**Comment by abhisheks008** [comment]
Issue assigned to you @deeptiii13. Go ahead!

**Comment by ayan-joshi** [comment]
Hey, I would like to work on this issue.
Full name : Ayan Joshi
GitHub Profile Link : https://github.com/ayan-joshi
Email ID : ayanjoshi182003@gmail.com
Approach for this Project : First I will train the model with basic method then to improve accuracy I will try with different algorithm such as Logistic Regression, SVM , naives, 
What is your participant role? SSOC
Please assign me this issue @abhisheks008

**Comment by abhisheks008** [comment]
You need to work on deep learning models as the project repository demands projects based on deep learning concepts. Also you have assigned to an issue, first complete that then only you will be able to work on another issue here.
@ayan-joshi

**Comment by achrekarom12** [comment]
Full name : Om Achrekar
GitHub Profile Link : https://github.com/achrekarom12
Email ID : achrekarom@gmail.com
Participant ID (if applicable):
Approach for this Project : I will use four techniques for sentiment analysis which are VADER, Simple Neural Network, Convolutional Neural Network and LSTM. This will give us a good comparison between iMDB reviews. I will also try to visualise the data in good way as there are only two columns.

**Comment by abhisheks008** [comment]
Issue assigned to you @achrekarom12
