### ISSUE TITLE
Pneumonia Detection from X-Ray

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/DL-Simplified#16]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Pneumonia Detection from X-Ray</br>
:red_circle: **Aim** : The aim is to create a DL model which will detect the pneumonia from the given X-ray images.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/paultimothymooney/chest-xray-pneumonia</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ESHA1101** [comment]
I am Esha and I would like to take up this issue
My GitHub: https://github.com/ESHA1101
Email ID: 20bcs045@iiitdwd.ac.in
Approach: this project is mainly based on image processing and knowledge on pneumonia and how it shows in x rays. I will formulate a few algorithms based on the latter and will check the accuracy using each algorithm. The model that gives the best accuracy will be chosen.
I am a participant of ssoc 2022

**Comment by abhisheks008** [comment]
We'll start the journey after completing those formalities. Till then, stay tuned with Deep Learning Simplified.

Thanks and regards.

**Comment by abhisheks008** [comment]
@ESHA1101 updates please.

**Comment by abhisheks008** [comment]
Updates please @ESHA1101

**Comment by PiyushBL45t** [comment]
Hey, @abhisheks008  I would like to work on this issue,

Full name : Piyush Bhujbal
GitHub Profile Link : https://github.com/PiyushBL45t
Email ID : bhujbalpiyush@gmail.com
Approaches for this Project :- 
- Read the images.
- Perform analysis of data.
- Check for reshaping and implement changes if needed.
- Create model architecture for the image dataset.
- Create image data for preprocessing.
- Make predictions.
- Check the accuracy and loss parameter for the model.
- Make live detection using OpenCV if possible.

What is your participant role: contributor at SWOC 3.0

**Comment by abhisheks008** [comment]
Assigned @PiyushBL45t

**Comment by nk-droid** [comment]
I would like to work on this under SSoC. Please assign me this project.

**Comment by nk-droid** [comment]
@abhisheks008 I'm working on my previously create issues. I want to work on this one too. Could you please me this as well?

**Comment by abhisheks008** [comment]
No, a contributor can not be assigned to more than one issue.
@nk-droid

**Comment by PiyushBL45t** [comment]
Hi, @abhisheks008, I would like to work on this issue and I will complete it for the Social Summer of Code. Please assign me this issue.

**Comment by abhisheks008** [comment]
Sure @PiyushBL45t. Let the previous PR merged.
