### ISSUE TITLE
Website UI is not good

### ISSUE THREAD

**Issue by MohamedMafaz** [World-of-ML/DL-Simplified#168]
Basically I am a UI Designer. I exclaimed that this repo have lot of deep learning projects. But, they are not indexed correctly in website. So I fix it

**Comment by abhisheks008** [comment]
Do you gonna create a new website for this project repo? Coz the existing one is built on Google sites just to show case the collection of the projects and a small FAQ section for the contributors. Can you brief your work procedure and approach?
@MohamedMafaz

**Comment by MohamedMafaz** [comment]
Creating new website is not that too easy

**Comment by MohamedMafaz** [comment]
I'll fix it if you give me the access for Google Sites

**Comment by MohamedMafaz** [comment]
Otherwise, If you need a professional website we can do that as freelancing project

**Comment by abhisheks008** [comment]
Well I like your approach, the main motive of this project repo is deep learning projects. In future if it really requires a proper website then will definitely let you know.

Thanks for showing interest. Closing the issue.

**Comment by MohamedMafaz** [comment]
If you assign me this issue I'll create you a website for free

**Comment by abhisheks008** [comment]
Will let you know when it is required. Right now, the main focus is on the dep learning projects.
