### ISSUE TITLE
Stock Price Prediction 

### ISSUE THREAD

**Issue by Volcano-Dragon** [World-of-ML/DL-Simplified#171]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Stock Price Prediction</br>
:red_circle: **Aim** : Predict Stock Price Using Past History of Stock Price</br>
:red_circle: **Dataset** : https://finance.yahoo.com/quote/TTM/history?p=TTM</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
What are the different DL models you are gonna use here?
@Volcano-Dragon

**Comment by Volcano-Dragon** [comment]
> What are the different DL models you are gonna use here? @Volcano-Dragon

I will use different types of RNN models because, in this algorithm, previous data (output) is required. For that, RNN is required to be more specific. LSMT is perfect for these predictions.

**Comment by abhisheks008** [comment]
Cool, issue has been assigned to you @Volcano-Dragon
