### ISSUE TITLE
Human Action Recognition

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/DL-Simplified#18]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Human Action Recognition</br>
:red_circle: **Aim** : Create a DL model which will identify the actions made by the humans.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/meetnagadia/human-action-recognition-har-dataset</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by sid6602** [comment]
Name: Siddhi Mankar
Github link:- https://github.com/sid6602
Email Id: siddhi.mankar@mitaoe.ac.in
Approach: To detect different actions of human being
role: contributor

**Comment by sankalp-srivastava** [comment]
@sid6602 Issue assigned to you. Try experimenting with different dl algorithms. See what gives a better result.

**Comment by sid6602** [comment]
Thank you @sankalp-srivastava

**Comment by abhisheks008** [comment]
@sid6602 updates please.

**Comment by sid6602** [comment]
Hello @abhisheks008, I am working on this issue. Will update you as soon an algorithms will be ready. Sorry for inconvenience.

**Comment by abhisheks008** [comment]
Updates please @sid6602

**Comment by sid6602** [comment]
@abhisheks008 Pull Request created.

**Comment by Khushi771** [comment]
Full name : Khushi Agarwal
GitHub Profile Link : https://github.com/Khushi771
Email ID : khushiag999@gmail.com
Approach for this Project :  Create a model which will identify the actions with good accuracy.
What is your participant role? Contributor

**Comment by abhisheks008** [comment]
Issue assigned to you @achrekarom12
