### ISSUE TITLE
Staircases Segmentation using DL

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/DL-Simplified#217]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Staircases Segmentation</br>
:red_circle: **Aim** : Create a DL model which will segment the staircases in ascending or descending order.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/akshaydattatraykhare/ascending-and-descending-staircases</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by OWAIS-THEGREAT** [comment]
Full name: Mohammed Owais
GitHub Profile Link: https://github.com/OWAIS-THEGREAT
Email ID : [mohammedowais6361@gmail.com](mailto:mohammedowais6361@gmail.com)
Participant ID (if applicable): Not applicable
Approach for this Project :

First I will analyze the datasets in the link.
Then I will remove those pictures that are not suitable for processing.
Then I will preprocess the data to make it suitable for the Models.
In my opinion, the best approach is to apply CNN to this dataset.
Then I will use different parameters to get the best results.
Will provide the most accurate model for this repo.
I think I have the required amount of knowledge for this issue.
What is your participant role? (Mention the Open Source program)
SSOC'23

**Comment by abhisheks008** [comment]
I have assigned you an issue. After completing that, you can work on this, as one issue at a time.

**Comment by kanishkakataria** [comment]
Full Name: Kanishka Kataria
GitHub Profile Link: https://github.com/kanishkakataria
Email :[([kanishka.kataria99@gmail.com](mailto:kanishka.kataria99@gmail.com))]

Approach for this project:
I will perform an in-depth exploratory data analysis .

I will augment the images, resize the images if necesary ,flip and rotate to train the models with more image train data.

Normalizing pixel values will be covered under preprocessing.

Then I will select 3-4 deep learning algorithms suitable for object detection.

A comparative study of all the models for classification like resnet 50, vggnet,cnn,mobilenet,decision tree.

Hyper tuning will be done for better performance of the models.Measuring relevant metrics such as precision, recall, and F1 score, I will compare the effectiveness of the different algorithms.

What is your participant role: contributor SSOC

Kindly assign the issue to me.

**Comment by abhisheks008** [comment]
> Full Name: Kanishka Kataria GitHub Profile Link: https://github.com/kanishkakataria Email :[([kanishka.kataria99@gmail.com](mailto:kanishka.kataria99@gmail.com))]
> 
> Approach for this project: I will perform an in-depth exploratory data analysis .
> 
> I will augment the images, resize the images if necesary ,flip and rotate to train the models with more image train data.
> 
> Normalizing pixel values will be covered under preprocessing.
> 
> Then I will select 3-4 deep learning algorithms suitable for object detection.
> 
> A comparative study of all the models for classification like resnet 50, vggnet,cnn,mobilenet,decision tree.
> 
> Hyper tuning will be done for better performance of the models.Measuring relevant metrics such as precision, recall, and F1 score, I will compare the effectiveness of the different algorithms.
> 
> What is your participant role: contributor SSOC
> 
> Kindly assign the issue to me.

Issue assigned to you @kanishkakataria
