### ISSUE TITLE
Anti Spoofing Project using DL

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/DL-Simplified#231]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Anti Spoofing Project</br>
:red_circle: **Aim** : Create a DL model which will identify the real image, replay, layout and cut out.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/tapakah68/anti-spoofing</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by rafiya2003** [comment]
I would like to work on this, frankly I don't know much but I will learn and do. I am a newbie(first year UG student). I want to learn and grow. please give me the opportunity to learn and experience

**Comment by abhisheks008** [comment]
Please do not to spam in every single issue. This might cause escalation as you are breaching Code of Conduct and Contribution Guidelines.

@rafiya2003

**Comment by SaketGudimella** [comment]
Full name : Gudimella Saketa Sri Ramacharyulu
GitHub Profile Link : https://github.com/SaketGudimella
Email ID : radhasaket38@gmail.com
Participant ID (if applicable): d4880732-5d70-48ba-a05e-a68cb5508a2b
Approach for this Project : 

I would be implementing this Anti-Spoofing project, with 3 specific DL algorithms -  1) Convolutional Neural Networks (CNNs), 2) Recurrent Neural Networks (RNNs), and 3) Siamese Networks. I will use the CNNs to extract the discriminative features from the images and classify them into different categories,the RNNs will be applied to capture temporal dependencies in sequential data, such as videos and the Siamese networks will be used to compare input images with reference images and determine their similarity or difference.

What is your participant role? SSoC'23 (Contributor)

**Comment by abhisheks008** [comment]
Issue assigned to you @SaketGudimella
