### ISSUE TITLE
PPI Documents Classification

### ISSUE THREAD

**Issue by nk-droid** [World-of-ML/DL-Simplified#244]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** :  An image classification model to classify PPI documents (Aadhaar Card, Pan Card, Driving License, Passport and Voter ID)</br>
:red_circle: **Aim** : Create an efficient CNN model to predict if an image is of Aadhaar Card, Pan Card, Driving License, Passport or Voter ID</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/mehaksingal/personal-identification-image-dataset-for-india</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Nidhish Kumar
- GitHub Profile Link :  https://github.com/nk-droid
- Email ID : nidhish.22k@gmail.com
- Participant ID (if applicable):
- Approach for this Project : First, I'll use some CNN models to create an efficient model. If they don't work, I'll use transfer learning.
- What is your participant role? SSoC'23 Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Hi @nk-droid nice to have you. I have assigned the tag `SSOC` to it, and this will be assigned to you by June 1, once the program starts officially.

**Comment by abhisheks008** [comment]
Issue assigned to @nk-droid
