### ISSUE TITLE
Housing Prices Prediction 

### ISSUE THREAD

**Issue by starkver23** [World-of-ML/DL-Simplified#258]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** :  Create a house price prediction model using python and jupyter notebooks</br>
:red_circle: **Aim** : To track the prices of houses over the past few years focusing on Sydney and Melbourne</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/shree1992/housedata and a CSV file from kaggle</br>
:red_circle: **Approach** : Try to use 3-4 algorithms mainly regressions to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by starkver23** [comment]
I am new to ML and DL, so I can try to use Multilayer Perceptron (MLP) in this project
@abhisheks008

**Comment by abhisheks008** [comment]
As the project repository demands projects in deep learning, simple machine learning approach will not work here.

You can learn the things and come after few time for this issue. This issue will be open for you only.
@starkver23

**Comment by Vansh912** [comment]
Full name : Vansh Tiwari
GitHub Profile Link : https://github.com/Vansh912
Email ID : vanshtiwari.912@gmail.com
Participant ID (if applicable):
Approach for this Project : will start by exploring the dataset and do preprocessing according to the requirement, will use arima model or regression models for comparision 
What is your participant role? (Mention the Open Source program): SSOC 23

**Comment by achrekarom12** [comment]
Full name : Om Achrekar
GitHub Profile Link : https://github.com/achrekarom12
Email ID : [achrekarom@gmail.com](mailto:achrekarom@gmail.com)
Participant ID (if applicable):
Approach for this Project : As this repository is about Deep Learning, I will implement CNN which will definitely yield higher accuracy than traditional multiple linear regression approach. At the end I will also show a comparison between these two approaches.

**Comment by arpy8** [comment]
Full name :
GitHub Profile Link : github.com/arpy8
Email ID : arpitsengar99@gmail.com
Participant ID (if applicable):
Approach for this Project : Performing EDA on the dataset and finally creating a model using Multivariable Regression
What is your participant role? (Mention the Open Source program) : SSOC 2023
