### ISSUE TITLE
Predict the Time of the Day using DL

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/DL-Simplified#267]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Predict the Time of the Day using DL</br>
:red_circle: **Aim** : Create a prediction model using DL algorithms to find out the time of the day.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/aymenkhouja/timeofdaydataset</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by SaketGudimella** [comment]
Full name : Gudimella Saketa Sri Ramacharyulu
GitHub Profile Link : https://github.com/SaketGudimella
Email ID : radhasaket38@gmail.com
Participant ID (if applicable): d4880732-5d70-48ba-a05e-a68cb5508a2b
Approach for this Project : 
1) Acquiring the dataset --> 2) Performing exploratory data analysis --> 3) Preprocessing the data --> 4) Considering the usage of models (RNNs) such as LSTM and GRU (which are good choices for time-based predictions) --> 5) Training the models with the prepared data --> 6) Evaluating their performance -->  7) Selecting the best-performing model.
 
What is your participant role? (Mention the Open Source program) - SSoC'23

**Comment by abhisheks008** [comment]
Issue assigned to you @SaketGudimella

**Comment by SaketGudimella** [comment]
Thank you sir for assigning me the issue.

**Comment by SaketGudimella** [comment]
@abhisheks008 I've raised a pull request please review and merge this pull request. Thank you !

Also, I've followed a different approach in solving this problem by using SVC, KNeighborsClassifier, and RandomForestClassifier because it felt better suited for this project.
