### ISSUE TITLE
Tweet Analysis of Indian Political Parties

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/DL-Simplified#268]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Tweet Analysis of Indian Political Parties</br>
:red_circle: **Aim** : Create a deep learning project which will identify the scenarios of tweets of the political parties in India using NLP.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/aryansingh0909/indian-political-party-tweets-daily-updated</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by achrekarom12** [comment]
Full name : Om Ramesh Achrekar
GitHub Profile Link : https://github.com/achrekarom12
Email ID : [achrekarom@gmail.com](mailto:achrekarom@gmail.com)
Participant ID (if applicable):
Approach for this Project : A sentiment analysis can be done using various NLP techniques to understand underlying trends and patterns. The dataset contains tweets of three major national political parties. A detailed study can be done for these three parties.

**Comment by abhisheks008** [comment]
Issue assigned to you @achrekarom12
