### ISSUE TITLE
Vegetable Image Classification

### ISSUE THREAD

**Issue by aditya0929** [World-of-ML/DL-Simplified#282]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** :  Vegetable Image Classification</br>
:red_circle: **Aim** : to predict correct vegetable names  corresponding to their images </br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/misrakahmed/vegetable-image-dataset</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aditya0929** [comment]
- Full name : Aditya Narayan Jha
- GitHub Profile Link : https://github.com/aditya0929
- Email ID : adityajha8906@gmail.com
- Participant ID (if applicable):
- Approach for this Project : I would be using cnn to make the models and for alternative methods i would choose to include architectures between mobileNet, ResNet , Alexnet or Vgg apart from adding convulational layers.  i will make comparison graphs between different models for easier understanding .                                
- What is your participant role? SSOC-2023

**Comment by abhisheks008** [comment]
Issue assigned to you @aditya0929
