### ISSUE TITLE
American Sign Language Detection

### ISSUE THREAD

**Issue by aditya0929** [World-of-ML/DL-Simplified#312]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** :  American Sign Language Detection </br>
:red_circle: **Aim** : to correctly predict the sign language images given in the dataset</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/ayuraj/asl-dataset </br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aditya0929** [comment]
Full name : Aditya Narayan Jha
GitHub Profile Link : https://github.com/aditya0929
Email ID : adityajha8906@gmail.com
Participant ID (if applicable): 
Approach for this Project : i would be making multi instance  image detection models as there are approx 36 classes of sign language from (0-9) and (A-Z) based on cnn and other deep learning architectures such as inception, resnet etc for the the best optimal accuracy.
What is your participant role? SSOC-23

**Comment by abhisheks008** [comment]
Issue assigned to you @aditya0929
