### ISSUE TITLE
Mushroom Classification using Deep Neural Networks

### ISSUE THREAD

**Issue by PiyushBL45t** [World-of-ML/DL-Simplified#319]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Mushroom Classification using Deep Learning
:red_circle: **Aim** : Classify 9 kinds of Mushroom species using Deep Learning and Computer Vision
:red_circle: **Dataset** : https://www.kaggle.com/datasets/lizhecheng/mushroom-classification
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Piyush Bhujbal
- GitHub Profile Link : https://www.github.com/PiyushBL45t
- Email ID : bhujbalpiyush@gmail.com
- Participant ID (if applicable): 
- Approach for this Project : 
    * First I shall visualize the images using various visuals.
    * Then create train, test and valid sets from the dataset.
    * Use the Deep Neural Algorithms like VGG16, MobileNetV2, EfficientNet50 for classification.
    * Perform classification and plot the results using Matplotlib image plots.
- What is your participant role? (Mention the Open Source program) : SSOC 2023 Participant

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Issue assigned to you @PiyushBL45t

**Comment by PiyushBL45t** [comment]
Thank you for your email.
