### ISSUE TITLE
 Market Basket Analysis

### ISSUE THREAD

**Issue by vaishnavi-3969** [World-of-ML/DL-Simplified#327]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : </br>
 Market Basket Analysis using Python

:red_circle: **Aim** : </br>
Implementation of Market Basket Analysis to discover associations and patterns between items in a transactional dataset

:red_circle: **Dataset** : </br>
Using a transactional dataset containing information about customer purchases. The dataset will include records of individual transactions, with each transaction containing a list of items purchased.

:red_circle: **Approach** : Using 2 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. 
1. Performing Exploratory Data Analysis (EDA) on the dataset to gain insights into the data and understand its structure. Analyzing the frequency of items, item combinations, and other relevant statistics.
2. Preprocessing the dataset to transform it into a suitable format for market basket analysis. This may involve converting the data into a binary matrix or transaction format, where each row represents a transaction and each column represents an item, with values indicating whether an item was present in a transaction.
3. Applying different algorithms for market basket analysis, such as Apriori algorithm and FP-Growth algorithm. 
4. Generating association rules from the analyzed dataset. Using metrics like support, confidence, and lift to identify significant associations between items. Extracting meaningful insights and patterns from the association rules.
5. Compare the performance and results of the implemented algorithms. Evaluating the efficiency and scalability of each algorithm. 

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Vaishnavi Kale
- GitHub Profile Link : https://github.com/vaishnavi-3969
- Email ID : vaishnavi.kale3011@gmail.com
- Participant ID (if applicable):
- Approach for this Project : Performing EDA, and performing different algorithms to evaluate the efficiency
- What is your participant role? (Mention the Open Source program)
Participant/Contributor - SSOC'23
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Issue assigned to you @vaishnavi-3969
