### ISSUE TITLE
Amazon Reviews Sentiment Analysis

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/DL-Simplified#33]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Amazon Reviews Sentiment Analysis</br>
:red_circle: **Aim** : Analyze the sentiments from the given dataset of Amazon</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/tarkkaanko/amazon</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by tknishh** [comment]
Full name : Tanish Khandelwal
GitHub Profile Link : https://github.com/tknishh
Email ID : tanishkhandelwaltk012@gmail.com
Participant ID (if applicable): NA
Approach for this Project : I've already worked on Sentiment analysis with IMDb movie review dataset (https://github.com/tknishh/IMDb-Review-Analysis) and would really like to use recent algorithms to implement models on some this Amazon review dataset.

**Comment by abhisheks008** [comment]
Hey @tknishh thanks for showing interest in this project repo. I'm just waiting for the formalities to be done by the SSOC team side, once it gets over we will start this journey.

Best wishes ✨

**Comment by Nikita-Shrma** [comment]
Hey @abhisheks008 I want to contribute in this project.
Please allow me

**Comment by abhisheks008** [comment]
Issue assigned to you @Nikita-Shrma

**Comment by fykaa** [comment]
Full name : Fyka Ansari
GitHub Profile Link : https://github.com/fykaa
Email ID : faeka6@gmail.com
Participant ID (if applicable): na
Approach for this Project : I'll use a variety of DL techniques and try to do my best. I have little experience with Deep Learning, so it may take some time to implement. Essentially, I want to use a library for sentiment analysis and perform exploratory data analysis for data cleaning/feature engineering before splitting the dataset, training the model, deploying it, and evaluating the customer churn prediction. Hopefully, my interest lies around this issue, will be happy to complete it.
What is your participant role? Social Summer of Code Participant

**Comment by abhisheks008** [comment]
@Nikita-Shrma updates please.

**Comment by Nikita-Shrma** [comment]
Sir,
I was 1st learning about github like how to fork,clone etc. and then I
learnt the concepts of ML and semantics libraries and web scrappping and
now I am able to apply most basic algorithm semantics analysis using naive
bayes and now I'm learning other algorithms.
Please provide me more time as my college are also going on .

Hoping for your kind consideration.

Thanks and Regards
Nikita Sharma

**Comment by abhisheks008** [comment]
Great going, carry on. Try to learn more and more and implement accordingly @Nikita-Shrma. All the best.

**Comment by Nikita-Shrma** [comment]
Thanks a lot sir.

**Comment by abhisheks008** [comment]
Updates please @Nikita-Shrma

**Comment by Nikita-Shrma** [comment]
Sir,
I'm sorry sir for late reply .Actually my exams are going on and earlier
lab exams were there and all the thing is happening without a single day
break.

I'm sorry for that, I was not able to do extra now.All I have done is
watched some you tube videos after naivebayes.

Thanks and Regards
Nikita Sharma

**Comment by abhisheks008** [comment]
Well then focus on your exams for now. If you are free later on you can take up other issues here, currently I'm unassigning the issue from you. All the best for your exams, give your best shot :100:

@Nikita-Shrma

**Comment by rutikal** [comment]
I would like to contribute on this issue.

**Comment by aishwarya1735** [comment]
Can this issue be assigned to me

**Comment by aishwarya1735** [comment]
Yes I'll do that today and give the details in the given format.

Also , could you let me know if my devfolio details were verified.

Thank you.

**Comment by abhisheks008** [comment]
Have you filled that form which I have shared in the email/discord channel. If yes, then your devfolio should be verified soon.
@aishwarya1735

**Comment by aishwarya1735** [comment]
Full name: M.V.N.S.Aishwarya
GitHub Profile Link: https://github.com/aishwarya1735
Email ID: ***@***.***
Participant ID (if applicable): NA
Approach for this Project: I would fetch the dataset and consider positive
and negative reviews of amazon based on different parameters like rating
(numbers), and feedback (words) and accordingly get the overall feedback
from the data.
What is your participant role?: Social Summer of Code Participant
.
.
.
Yes, I have filled the form sent to the mail.

**Comment by sankalp-srivastava** [comment]
@aishwarya1735 issue assigned to you.

**Comment by abhisheks008** [comment]
@aishwarya1735 this issue was assigned to you 2 days back, and will remain assigned to you. Keep going with your project, don't worry I'll not unassign you this issue.

**Comment by aishwarya1735** [comment]
Thank you for the clarification. I am working on it 👍🏻

**Comment by SHAY2407** [comment]
Full Name: Yashwardhan Khanna
GitHub URL: https://github.com/SHAY2407
Email ID: yashwardhan2407@gmail.com
Role: SWOC 3.0 Participant
Approach: I will first try with a simpler approach by using python libraries such as NTLK, TextBlob or VaderSentiment, if i complete that i can move on to use self made logistic regression or SVM model

**Comment by abhisheks008** [comment]
Issue assigned to you @SHAY2407
