### ISSUE TITLE
ChatGPT-Based Tweets Sentiment Analysis Using DL

### ISSUE THREAD

**Issue by vrinda-vritti** [World-of-ML/DL-Simplified#345]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : ChatGPT-Based Tweets Sentiment Analysis
:red_circle: **Aim** : Analysing the Tweets  about ChatGPT and the performing the Sentiment Analysis 
:red_circle: **Dataset** : https://www.kaggle.com/datasets/tariqsays/chatgpt-twitter-dataset 
:red_circle: **Approach** : Using Python libraries, such as Numpy and Pandas, visualise the Tweets and then perform the Sentiment Analysis on the tweets.
**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Vrinda Vritti
- GitHub Profile Link : https://github.com/vrinda-vritti
- Email ID : vrinda.v0221@gmail.com
- Participant ID (if applicable): - 
- Approach for this Project : Performing Sentiment Analysis on the Tweets on ChatGPT
- What is your participant role? (Mention the Open Source program) : Social Summer Of Code Season 2

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
What kind of deep learning models are you planning to use here?
@vrinda-vritti

**Comment by Nabanita29** [comment]
Full name : Nabanita
GitHub Profile Link : https://github.com/Nabanita29/
Email ID : nabanita21csu057@ncuindia.edu
Participant ID (if applicable): - 
Approach for this Project : I will analyze the ChatGPT-based tweets dataset using Python libraries like Numpy and Pandas. I will perform sentiment analysis on the tweets to determine the sentiment associated with ChatGPT. For this, I can use different models like BoW, TF-IDF, Word2Vec, LSTM, or BERT. 
What is your participant role? (Mention the Open Source program) : Social Summer Of Code Season 2

**Comment by vrinda-vritti** [comment]
> What kind of deep learning models are you planning to use here? @vrinda-vritti

Hi, sorry for replying back late. I can apply LSTM, BiLSTM, BERT, and Electra to the dataset, and rest assured, the preprocessing of the data has already been done.

**Comment by abhisheks008** [comment]
> > What kind of deep learning models are you planning to use here? @vrinda-vritti
> 
> Hi, sorry for replying back late. I can apply LSTM, BiLSTM, BERT, and Electra to the dataset, and rest assured, the preprocessing of the data has already been done.

Thanks for letting me know. Issue assigned to you @vrinda-vritti 

@Nabanita29 you can try up other issues or you can create an issue by your own.
