### ISSUE TITLE
Indian Trucks Detection

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/DL-Simplified#46]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Indian Trucks Detection</br>
:red_circle: **Aim** : Create a image classification model which will identify the images of the trucks.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/aneeshtickoo/indian-trucks</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by PrathmeshN99** [comment]
Full name : Prathmesh Nagpure
GitHub Profile Link : www.github.com/PrathmeshN99
Email ID : prathmesh99.pn@gmail.com
Participant ID (if applicable):
Approach for this Project : I would like to work on this issue. This would help in employing various deep learning techniques and algorithms and create the best of this project. 
What is your participant role? (Mention the Open Source program)

**Comment by LahariBoni** [comment]
Assigned it to you @PrathmeshN99. Please mention "SSOC" for the participant role.

**Comment by abhisheks008** [comment]
@PrathmeshN99 updates please.

**Comment by abhisheks008** [comment]
Updates please @PrathmeshN99

**Comment by abhisheks008** [comment]
@PrathmeshN99 updates please.

**Comment by PiyushBL45t** [comment]
Hey, @abhisheks008
I would like to work on this project. If you haven't assigned this issue to anyone, let me work on this

Full name : Piyush Bhujbal
GitHub Profile Link: https://github.com/PiyushBL45t
Email ID: bhujbalpiyush@gmail.com
Approach for this Project:

- Perform EDA.
- Perform Image visualization operations.
- Create models and check for their accuracy.
- Perform image detection.

Participant Role: Contributor at SWOC 3.0

**Comment by abhisheks008** [comment]
Issue assigned to you @PiyushBL45t 
Go ahead!
